VPATH = .:RCS:Build/

.SUFFIXES:
.SUFFIXES: .o .F90 .f90 .F .f .H .h  .c


# Tests dont work with unix make ? (works with gmake ...)
include ../Make.Inc/make.inc

# This is the hycom utility library
# NB: Path is relative to TMP dir
LIBS:= -L../../../lib/ -lhycnersc $(LIBS)

# This is the hycom utility includes (modules)
# NB: Path is relative to TMP dir
INCLUDE:= -I../ -I../../../include/ -I./ $(INCLUDE)

# Set specific flag SOUP is high resolution and frequency wind from oceanweather
#CPPFLAGS:=$(CPPFLAGS) -USOUP -DKARALIGHT
CPPFLAGS:=$(CPPFLAGS) 

# AIX (xlf) peculiarities. NB: Only necessary for Fortran files
ifneq (,$(findstring -DAIX,$(CPPFLAGS)))
   subs=-WF,-
   CPPFLAGS:=$(subst -,$(subs),$(CPPFLAGS))
endif

.F.o:
	cd ./TMP ; $(CF90) -c $(INCLUDE) $(CPPFLAGS) $(FFLAGS) $(F77FLG) -o $*.o  ../$<

.F90.o:
	cd ./TMP ; $(CF90) -c $(INCLUDE) $(CPPFLAGS) $(FFLAGS) $(F90FLG) -o $*.o  ../$<

.f.o:
	cd ./TMP ; $(CF90) -c $(INCLUDE) $(FFLAGS) $(F77FLG) -o $*.o  ../$<



TARGET2=force_perturb-2.2

all:  $(TARGET2)

#################################################################################
#OBJECTS =\
#
#$(TARGET): $(OBJECTS) 
#	cd Build/ ; $(LD) $(LINKFLAGS) -o ../$(TARGET) $(OBJECTS) $(LIBS)
#################################################################################
OBJECTS2= \
	mod_xc.o \
	mod_za.o \
	mod_parameters.o \
	spherdist.o \
	wtime.o \
	mod_grid.o \
	mod_year_info22.o \
	m_parse_blkdat.o   \
	mod_forcing_nersc.o   \
	mod_pseudo.o \
	mod_random_forcing.o   \
	p_force_perturb.o \
	dayfor.o
$(TARGET2): $(OBJECTS2) 
	cd ./TMP ; $(LD) $(LINKFLAGS) -o ../$(TARGET2) $(OBJECTS2) $(LIBS)
#################################################################################

install : all
	mkdir -p ../../bin/
	cp $(TARGET2) ../../bin/

clean:
	rm ./TMP/*.o ./TMP/*.mod  $(TARGET2)

